services:
  - type: web
    name: trevel-roleplay-bot
    env: node
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TOKEN
        fromDatabase: true   # Esto indica que Render usará la variable que configures en su panel
